sudo: required

services:
  - docker
  
env:
  DOCKER_COMPOSE_VERSION: 1.21.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
#   - pip install --user coveralls

script:
  - echo "TRAVIS_JOB_ID=\"$TRAVIS_JOB_ID\"" >> .env
  - echo "TRAVIS_BRANCH=\"$TRAVIS_BRANCH\"" >> .env
  - echo "TRAVIS=\"$TRAVIS\"" >> .env
  - echo "CI=\"$CI\"" >> .env
  - echo "CONTINUOUS_INTEGRATION=\"$CONTINUOUS_INTEGRATION\"" >> .env
  - echo "TRAVIS_COMMIT=\"$TRAVIS_COMMIT\"" >> .env
  - echo "TRAVIS_COMMIT_MESSAGE=\"$TRAVIS_COMMIT_MESSAGE\"" >> .env
  - echo "TRAVIS_JOB_NUMBER=\"$TRAVIS_JOB_NUMBER\"" >> .env
  - echo "TRAVIS_BUILD_ID=\"$TRAVIS_BUILD_ID\"" >> .env
  - echo "TRAVIS_BUILD_NUMBER=\"$TRAVIS_BUILD_NUMBER\"" >> .env
  - echo "TRAVIS_REPO_SLUG=\"$TRAVIS_REPO_SLUG\"" >> .env
  - echo "TRAVIS_PULL_REQUEST=\"$TRAVIS_PULL_REQUEST\"" >> .env
  - echo "TRAVIS_PULL_REQUEST_BRANCH=\"$TRAVIS_PULL_REQUEST_BRANCH\"" >> .env
  - echo "TRAVIS_PULL_REQUEST_SHA=\"$TRAVIS_PULL_REQUEST_SHA\"" >> .env
  - echo "TRAVIS_PULL_REQUEST_SLUG=\"$TRAVIS_PULL_REQUEST_SLUG\"" >> .env
#   - echo "COVERALLS_REPO_TOKEN=\"$COVERALLS_REPO_TOKEN\"" >> .env
  - docker-compose build ckan
  - docker-compose up -d
  - sleep 10
  - docker-compose logs solr
  - docker-compose exec solr bin/solr create_core -c ckan -force
  - docker cp ./ckanext-hdx_search/ckanext/hdx_search/hdx-solr/schema.xml solr:/srv/solr/server/solr/ckan/conf/
  - docker cp ./docker/solrconfig.xml solr:/srv/solr/server/solr/ckan/conf/
  - docker-compose restart solr
  - sleep 20
  - docker-compose restart ckan
  - docker-compose exec ckan pip install --no-cache-dir -r /srv/ckan/dev-requirements.txt
  - docker-compose exec ckan python setup.py develop
  - docker-compose exec ckan hdxckantool plugins dev
  - docker-compose exec ckan hdxckantool pgpass
  - docker-compose exec ckan psql -h dbckan -U ckan -c "create database datastore owner ckan;"
  - docker-compose exec ckan psql -h dbckan -U ckan -c "create role datastore with login;"
  - docker-compose exec ckan psql -h dbckan -U ckan -c "alter role datastore with password 'datastore';"
  - docker-compose exec ckan hdxckantool db set-perms
  - docker-compose exec ckan paster db upgrade -c /etc/ckan/prod.ini
  - docker-compose exec ckan hdxckantool feature
  - docker-compose exec ckan hdxckantool less compile
  - docker-compose exec ckan sh -c "mkdir -p /srv/filestore/storage/uploads/group"
  - docker-compose exec ckan sh -c "touch /srv/filestore/storage/uploads/group/david_thumbnail.png"
  - docker-compose exec ckan nosetests ./ckanext-hdx_org_group/ckanext/hdx_org_group/tests -ckan --with-pylons=ckanext-hdx_org_group/test.ini.sample --logging-level=ERROR --with-coverage --cover-package=ckanext.hdx_org_group
  - docker-compose exec ckan nosetests ./ckanext-hdx_users/ckanext/hdx_users/tests -ckan --with-pylons=ckanext-hdx_users/test.ini.sample --logging-level=ERROR --with-coverage --cover-package=ckanext.hdx_users
  - docker-compose exec ckan echo $TRAVIS_BRANCH
  - docker-compose exec ckan echo $TRAVIS
  - docker-compose exec ckan python -c 'import os;print os.environ.get("TRAVIS")'
  - docker cp ckan:/srv/ckan/.coverage ./
  - docker-compose exec ckan coveralls
#   - ln -sf /home/travis/build/alexandru-m-g/hdx-ckan /srv/ckan
#   - coveralls
  
# after_success:
# - docker-compose exec ckan echo $TRAVIS_BRANCH  
